safe: false
permalink: /posts/:title.html
exclude:
  - README.md

name: luanheart
host: luanheart.com
desc: ╮(╯▽╰)╭

custom:
    category:
        default: default
        another: another
        vue: vue
        luan: luan
    categories:
      - name:  default
        title: 默认

      - name:  another
        title: 其他

      - name:  vue
        title: Vue笔记

      - name:  luan
        title: luan
        
    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: luanheart
        email: luanheartx@gmail.com
        disqus: luan             # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: luanheart                # GitHub账号
        gravatar: 4a04dacdcf97d2618bec72854fc82610  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
